services:
  - type: web
    name: jalskti-app
    env: python

    # --- THIS SECTION IS MISSING FROM YOUR FILE ---
    # It forces Python to print logs instantly, which we need for debugging.
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    # --------------------------------------------

    rootDirectory: backend
    buildCommand: |
      apt-get update && apt-get install -y libgdal-dev --no-install-recommends
      chmod -R 755 .
      pip install -r requirements.txt
    startCommand: gunicorn app:app
