services:
  - type: web
    name: rtwqms-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libgdal-dev --no-install-recommends
      chmod -R a+r backend
      pip install -r backend/requirements.txt
    startCommand: gunicorn --chdir backend app:app
